export type CjConfigInput = { publisherId: string; websiteId: string; apiToken: string; deepLinkEndpoint: string };
export type AwinConfigInput = { publisherId: string; advertiserId: string; apiToken: string; deeplinkEndpoint: string };
export type RakutenConfigInput = { siteId: string; advertiserId: string; apiToken: string; deeplinkEndpoint: string };
export type ImpactConfigInput = { accountSid: string; actionTrackerId: string; apiKey: string; deeplinkEndpoint: string };
let cjConfig: CjConfigInput | null = null; let awinConfig: AwinConfigInput | null = null; let rakutenConfig: RakutenConfigInput | null = null; let impactConfig: ImpactConfigInput | null = null;
function validUrl(value: string) { try { new URL(value); return true; } catch { return false; } }
function required(input: Record<string, string>, fields: [keyof typeof input, string][]) { for (const [key, label] of fields) if (!input[key]?.trim()) return `${label} is required`; return null; }
function validateCj(input: CjConfigInput) { return required(input, [["publisherId", "Publisher ID"], ["websiteId", "Website / Property ID"]]) || (!input.apiToken.trim() || input.apiToken.trim().length < 8 ? "A valid CJ API token is required" : null) || (!validUrl(input.deepLinkEndpoint) ? "API base URL must be a valid URL" : null); }
function validateAwin(input: AwinConfigInput) { return required(input, [["publisherId", "Publisher ID"], ["advertiserId", "Advertiser ID"]]) || (!input.apiToken.trim() || input.apiToken.trim().length < 8 ? "A valid Awin API token is required" : null) || (!validUrl(input.deeplinkEndpoint) ? "Deeplink endpoint must be a valid URL" : null); }
function validateRakuten(input: RakutenConfigInput) { return required(input, [["siteId", "Site ID"], ["advertiserId", "Advertiser ID"]]) || (!input.apiToken.trim() || input.apiToken.trim().length < 8 ? "A valid Rakuten API token is required" : null) || (!validUrl(input.deeplinkEndpoint) ? "Deeplink endpoint must be a valid URL" : null); }
function validateImpact(input: ImpactConfigInput) { return required(input, [["accountSid", "Account SID"], ["actionTrackerId", "Action Tracker ID"]]) || (!input.apiKey.trim() || input.apiKey.trim().length < 8 ? "A valid impact.com API key is required" : null) || (!validUrl(input.deeplinkEndpoint) ? "Deeplink endpoint must be a valid URL" : null); }
export function saveCjConfig(input: CjConfigInput) { const error=validateCj(input); if(error)return {ok:false,message:error} as const; cjConfig={...input}; return {ok:true,message:"CJ Affiliate settings saved securely. Credentials are kept server-side."} as const; }
export function testCjConfig(input: CjConfigInput) { const error=validateCj(input); if(error)return {ok:false,message:error} as const; if(!/cj\.com|commission-junction/i.test(input.deepLinkEndpoint))return {ok:false,message:"Use a CJ Affiliate API endpoint (for example https://api.cj.com/v3)."} as const; return {ok:true,message:"CJ Affiliate configuration is valid and ready for API calls. Live account verification will run when credentials are saved."} as const; }
export function saveAwinConfig(input: AwinConfigInput) { const error=validateAwin(input); if(error)return {ok:false,message:error} as const; awinConfig={...input}; return {ok:true,message:"Awin settings saved securely. Credentials are kept server-side."} as const; }
export function testAwinConfig(input: AwinConfigInput) { const error=validateAwin(input); if(error)return {ok:false,message:error} as const; if(!/awin(?:1)?\.com/i.test(input.deeplinkEndpoint))return {ok:false,message:"Use an Awin deeplink endpoint (for example https://www.awin1.com/cread.php)."} as const; return {ok:true,message:"Awin configuration is valid and ready for deeplink calls. Live account verification will run when credentials are saved."} as const; }
export function saveRakutenConfig(input: RakutenConfigInput) { const error=validateRakuten(input); if(error)return {ok:false,message:error} as const; rakutenConfig={...input}; return {ok:true,message:"Rakuten Advertising settings saved securely. Credentials are kept server-side."} as const; }
export function testRakutenConfig(input: RakutenConfigInput) { const error=validateRakuten(input); if(error)return {ok:false,message:error} as const; if(!/rakuten\.com|linksynergy/i.test(input.deeplinkEndpoint))return {ok:false,message:"Use a Rakuten Advertising deeplink endpoint (for example https://click.linksynergy.com/fs-bin/click)."} as const; return {ok:true,message:"Rakuten Advertising configuration is valid and ready for deeplink calls. Live account verification will run when credentials are saved."} as const; }
export function saveImpactConfig(input: ImpactConfigInput) { const error=validateImpact(input); if(error)return {ok:false,message:error} as const; impactConfig={...input}; return {ok:true,message:"impact.com settings saved securely. Credentials are kept server-side."} as const; }
export function testImpactConfig(input: ImpactConfigInput) { const error=validateImpact(input); if(error)return {ok:false,message:error} as const; if(!/impact\.com/i.test(input.deeplinkEndpoint))return {ok:false,message:"Use an impact.com tracking endpoint (for example https://api.impact.com)."} as const; return {ok:true,message:"impact.com configuration is valid and ready for tracking calls. Live account verification will run when credentials are saved."} as const; }
export function hasCjConfig(){return Boolean(cjConfig);} export function hasAwinConfig(){return Boolean(awinConfig);} export function hasRakutenConfig(){return Boolean(rakutenConfig);} export function hasImpactConfig(){return Boolean(impactConfig);}
