import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, router } from "./_core/trpc";
import { saveAwinConfig, saveCjConfig, saveImpactConfig, saveRakutenConfig, testAwinConfig, testCjConfig, testImpactConfig, testRakutenConfig } from "./integrationService";
import { getSyncedCjProducts, syncCjProducts } from "./cjCatalogService";
const cjInput=z.object({publisherId:z.string().trim().max(120),websiteId:z.string().trim().max(160),apiToken:z.string().trim().max(2000),deepLinkEndpoint:z.string().trim().url()});
const awinInput=z.object({publisherId:z.string().trim().max(120),advertiserId:z.string().trim().max(120),apiToken:z.string().trim().max(2000),deeplinkEndpoint:z.string().trim().url()});
const rakutenInput=z.object({siteId:z.string().trim().max(120),advertiserId:z.string().trim().max(120),apiToken:z.string().trim().max(2000),deeplinkEndpoint:z.string().trim().url()});
const impactInput=z.object({accountSid:z.string().trim().max(120),actionTrackerId:z.string().trim().max(120),apiKey:z.string().trim().max(2000),deeplinkEndpoint:z.string().trim().url()});
const cjSyncInput=z.object({apiToken:z.string().trim().max(2000),companyId:z.string().trim().max(120),pid:z.string().trim().max(120),keyword:z.string().trim().max(120).optional(),limit:z.number().int().min(1).max(50).optional()});
export const appRouter=router({system:systemRouter,auth:router({me:publicProcedure.query(opts=>opts.ctx.user),logout:publicProcedure.mutation(({ctx})=>{const cookieOptions=getSessionCookieOptions(ctx.req);ctx.res.clearCookie(COOKIE_NAME,{...cookieOptions,maxAge:-1});return{success:true} as const;})}),catalog:router({cjProducts:publicProcedure.query(()=>getSyncedCjProducts()),syncCj:publicProcedure.input(cjSyncInput).mutation(({input})=>syncCjProducts(input))}),integrations:router({testCj:publicProcedure.input(cjInput).mutation(({input})=>testCjConfig(input)),saveCj:publicProcedure.input(cjInput).mutation(({input})=>saveCjConfig(input)),testAwin:publicProcedure.input(awinInput).mutation(({input})=>testAwinConfig(input)),saveAwin:publicProcedure.input(awinInput).mutation(({input})=>saveAwinConfig(input)),testRakuten:publicProcedure.input(rakutenInput).mutation(({input})=>testRakutenConfig(input)),saveRakuten:publicProcedure.input(rakutenInput).mutation(({input})=>saveRakutenConfig(input)),testImpact:publicProcedure.input(impactInput).mutation(({input})=>testImpactConfig(input)),saveImpact:publicProcedure.input(impactInput).mutation(({input})=>saveImpactConfig(input))})});
export type AppRouter=typeof appRouter;
