import type { VercelRequest, VercelResponse } from "@vercel/node";
import { Pool } from "pg";

type Product = { id: string; title: string; description: string; price: string; currency: string; advertiserName: string; clickUrl: string; imageUrl: string; syncedAt: string };
const env = (...names: string[]) => names.map((name) => process.env[name]).find((value) => value?.trim())?.trim() || "";
const databaseUrl = () => env("DATABASE_URL", "POSTGRES_URL", "POSTGRES_PRISMA_URL", "SUPABASE_DB_URL");
const cleanUrl = (raw: string) => { try { const url = new URL(raw); ["sslmode", "sslcert", "sslkey", "sslrootcert"].forEach((key) => url.searchParams.delete(key)); return url.toString(); } catch { return raw; } };
const tag = (block: string, name: string) => block.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)</${name}>`, "i"))?.[1]?.replace(/<!\\[CDATA\\[|\\]\\]>/g, "").trim() || "";
const csv = (raw: string) => { const rows: string[][] = []; let row: string[] = [], field = "", quoted = false; for (let i = 0; i < raw.length; i++) { const char = raw[i], next = raw[i + 1]; if (char === '"' && quoted && next === '"') { field += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === ',' && !quoted) { row.push(field); field = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && next === "\n") i++; row.push(field); if (row.some((cell) => cell.trim())) rows.push(row); row = []; field = ""; } else field += char; } if (field || row.length) { row.push(field); rows.push(row); } return rows; };
const result = (res: VercelResponse, status: number, message: string, products: Product[] = []) => res.status(status).json({ ok: status < 400 && products.length > 0, message, products });

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader("Cache-Control", "no-store");
  if (req.method !== "GET" && req.method !== "POST") return result(res, 405, "Awin sync accepts GET or POST requests.");
  const feedUrl = env("AWIN_PRODUCT_FEED_URL", "AWIN_PRODUCT_FEED_LIST_URL");
  const token = env("AWIN_PRODUCT_FEED_API_KEY", "AWIN_PUBLISHER_API_TOKEN", "AWIN_API_TOKEN");
  const publisherId = env("AWIN_PUBLISHER_ID");
  const advertiserId = env("AWIN_ADVERTISER", "AWIN_ADVERTISER_ID");
  if (!feedUrl) return result(res, 503, "Awin feed URL is not configured. Add AWIN_PRODUCT_FEED_URL or AWIN_PRODUCT_FEED_LIST_URL in Vercel Production.");
  try {
    const url = new URL(feedUrl); if (publisherId && !url.searchParams.has("publisherId")) url.searchParams.set("publisherId", publisherId); if (advertiserId && !url.searchParams.has("advertiserId")) url.searchParams.set("advertiserId", advertiserId);
    const upstream = await fetch(url, { headers: { Accept: "text/csv, application/xml, application/json", ...(token ? { Authorization: `Bearer ${token}`, "X-Api-Key": token } : {}) } });
    const raw = await upstream.text(); if (!upstream.ok) return result(res, 502, `Awin product feed returned HTTP ${upstream.status}. ${raw.slice(0, 180)}`);
    const syncedAt = new Date().toISOString(); let products: Product[] = [];
    if (/json/i.test(upstream.headers.get("content-type") || "") || raw.trim().startsWith("[")) { const parsed = JSON.parse(raw) as any[]; products = parsed.slice(0, 24).map((item, i) => ({ id: String(item.id || item.productId || `awin-${i}`), title: String(item.title || item.name || "Awin partner product"), description: String(item.description || item.shortDescription || "Product from an Awin advertiser."), price: String(item.price || item.currentPrice || "View offer"), currency: String(item.currency || ""), advertiserName: String(item.advertiserName || item.merchantName || "Awin advertiser"), clickUrl: String(item.aw_deep_link || item.deepLink || item.url || item.productUrl || "#"), imageUrl: String(item.imageUrl || item.image || item.merchantImageUrl || ""), syncedAt })); }
    else if (/<product|<item/i.test(raw)) { const blocks = [...raw.matchAll(/<(?:product|item)\b[^>]*>([\s\S]*?)<\/(?:product|item)>/gi)].map((m) => m[1]); products = blocks.slice(0, 24).map((block, i) => ({ id: tag(block, "id") || tag(block, "aw_product_id") || `awin-${i}`, title: tag(block, "title") || tag(block, "name") || "Awin partner product", description: tag(block, "description") || "Product from an Awin advertiser.", price: tag(block, "price") || "View offer", currency: tag(block, "currency"), advertiserName: tag(block, "brand") || tag(block, "merchant") || "Awin advertiser", clickUrl: tag(block, "aw_deep_link") || tag(block, "link") || tag(block, "url") || "#", imageUrl: tag(block, "image_link") || tag(block, "image") || "", syncedAt })); }
    else { const rows = csv(raw); const headers = (rows.shift() || []).map((header) => header.trim().toLowerCase().replace(/[^a-z0-9]+/g, "_")); const value = (row: string[], names: string[]) => { const index = names.map((name) => headers.indexOf(name)).find((index) => index >= 0); return index === undefined ? "" : row[index] || ""; }; products = rows.slice(0, 24).map((row, i) => ({ id: value(row, ["id", "product_id", "aw_product_id"]) || `awin-${i}`, title: value(row, ["title", "name", "product_name"]) || "Awin partner product", description: value(row, ["description", "short_description"]) || "Product from an Awin advertiser.", price: value(row, ["price", "sale_price"]) || "View offer", currency: value(row, ["currency", "price_currency"]), advertiserName: value(row, ["brand", "merchant", "advertiser_name"]) || "Awin advertiser", clickUrl: value(row, ["aw_deep_link", "deep_link", "link", "url", "product_url"]) || "#", imageUrl: value(row, ["image_link", "image_url", "image"]) || "", syncedAt })); }
    const dbUrl = databaseUrl(); if (dbUrl && products.length) { const pool = new Pool({ connectionString: cleanUrl(dbUrl), ssl: { rejectUnauthorized: false }, max: 1 }); try { for (const product of products) await pool.query(`INSERT INTO tracked_links ("productId", "token", "source", "network", "externalLinkId", "campaign", "destinationUrl", "imageUrl", "linkStatus", "firstSeenAt", "lastSeenAt", "lastCheckedAt") VALUES (0, $1, $2, 'awin', $3, $4, $5, $6, 'active', NOW(), NOW(), NOW()) ON CONFLICT ("token") DO UPDATE SET "destinationUrl"=EXCLUDED."destinationUrl", "imageUrl"=EXCLUDED."imageUrl", "linkStatus"='active', "lastSeenAt"=NOW(), "lastCheckedAt"=NOW(), "lastCheckError"=NULL`, [`awin:${product.id}`, product.advertiserName, product.id, advertiserId || "product-feed", product.clickUrl, product.imageUrl]); } finally { await pool.end(); } }
    return result(res, products.length ? 200 : 502, products.length ? `Loaded ${products.length} Awin products.` : "Awin feed returned no usable products.", products);
  } catch (e) { return result(res, 502, e instanceof Error ? e.message : "Awin product feed request failed."); }
}
